# Generated by Django 4.2.6 on 2023-11-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='validity',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
