# Generated by Django 4.2.6 on 2023-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_passwordresettoken_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='validity',
            field=models.DateTimeField(),
        ),
    ]
