# Generated by Django 4.2.6 on 2023-11-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_passwordresettoken_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='validity',
        ),
    ]
