# Generated by Django 4.2.6 on 2023-12-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_passwordresettoken_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='validity',
        ),
    ]
